version: '3'
services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'

  redis:
    image: redis
    ports:
      - '6379:6379'
  
  # vinema:
  #   build: .
  #   image: vinema:vinema_api
  #   links:
  #     - mongo
  #   ports:
  #     - '3030:3030'
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./mongo-data:/var/lib/mongo/data
    